### ISSUE TITLE
Always report back metadata

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1202]
It would be nice to add a check to metadata query - `PythonPackageVersion.python_package_index_id is not Null` so we report back metadata found by *any* solver (it is possible one solver fails to obtain metadata due to installation issues on a Python interpreter, but another solver obtains package metadata when running a python interpreter in different version which does not cause installation issues). 

https://github.com/thoth-station/storages/blob/master/thoth/storages/graph/postgres.py#L3720-L3744

**Comment by bissenbay** [comment]
@fridex We are actually explicitly saying that that string can have a null value, for example: [1].
Maybe we should upgrade the version, :thinking: ? There is a change `Added clarifications to null not being a type (as opposed to a value).` in `OAS 3.0.0-rc1 Released!` [2]

[1] https://github.com/thoth-station/user-api/blob/master/openapi/openapi.yaml#L2037
[2] https://github.com/OAI/OpenAPI-Specification/releases

**Comment by fridex** [comment]
> @fridex We are actually explicitly saying that string can have a `null` value, for example: [1].
> Maybe we should upgrade the version of OpenAPI,  ? There is a change `Added clarifications to null not being a type (as opposed to a value).` in `OAS 3.0.0-rc1 Released!` [2]
> 
> [1] https://github.com/thoth-station/user-api/blob/master/openapi/openapi.yaml#L2037
> [2] https://github.com/OAI/OpenAPI-Specification/releases

You can try to specify `x-nullable` [1] as stated in https://github.com/zalando/connexion/issues/226, but not sure about our thamos client lib generated automatically out of sources (if it supports it). You can also try to set `type: [str, null]`.

[1] https://connexion.readthedocs.io/en/latest/request.html#nullable-parameters

**Comment by pacospace** [comment]
is it closed by https://github.com/thoth-station/storages/pull/1229/files?

**Comment by fridex** [comment]
Yes, this issue is closed by -  https://github.com/thoth-station/storages/pull/1229

But I don't know why my comment went to this issue as it corresponds to another one.
