### ISSUE TITLE
is this still required?

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#1210]
**Is your feature request related to a problem? Please describe.**
reduce dependencies

**Comment by fridex** [comment]
What do you mean by "this"?

**Comment by goern** [comment]
oh, I thought the issue would reference the line in Pipenv that I highlighted: https://github.com/thoth-station/storages/blob/master/Pipfile#L11

**Comment by fridex** [comment]
> oh, I thought the issue would reference the line in Pipenv that I highlighted: https://github.com/thoth-station/storages/blob/master/Pipfile#L11

We don't need it anymore :+1:
