### ISSUE TITLE
broken new_patch_release automation?!

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#1258]

**Comment by fridex** [comment]
Done in #1259. Closing this issue and releasing manually.

**Comment by harshad16** [comment]
@goern What is the issue here?

**Comment by goern** [comment]
it looks like some automation is not happening... maybe we just observe if releases are borken, it looks like the upload-pypi job was not triggered within the post or release pipeline... https://managesf.thoth-station.ninja/zuul/t/local/builds?project=thoth-station%2Fstorages

**Comment by harshad16** [comment]
Relates to #https://github.com/AICoE/Sefkhet-Abwy/pull/15 and PyPI not accepting the email id.

**Comment by harshad16** [comment]
Fixed by the AICoE/Sefkhet-Abwy#15 and also by setting a valid email id for sesheta at Pypi
