### ISSUE TITLE
new patch release

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#1282]

**Comment by goern** [comment]
@harshad16 seems like sesheta needs to work on this issue to do the release/upload...

**Comment by goern** [comment]
https://github.com/AICoE/sesheta/blob/bd16eec11d52baa6406299e1c0a15c5aca51e1a1/sesheta/webhooks.py#L149 is what we are missing...

**Comment by fridex** [comment]
@goern Should we close this?

**Comment by goern** [comment]
ne, I need it for testing
