### ISSUE TITLE
Migrate to PostgreSQL 10+

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1435]
**Is your feature request related to a problem? Please describe.**

Let's migrate our PG instances to version at least 10 to enable 0-downtime updates and automatic killing of long living transactions.

**Comment by fridex** [comment]
This one is fairly easy - we have backups and the service catalog on PSI has 10 as the latest version:

```
$ oc describe imagestreamtag -n openshift postgresql:latest                                                 
...                                                                                                     
		name=rhscl/postgresql-10-rhel7
...
```

Ideally, we should do the migration before #1437 

@harshad16 are you in? :)

**Comment by goern** [comment]
implemented by https://github.com/thoth-station/thoth-application/blob/master/core/overlays/cnv-prod/graph-prod/postgresql.yaml#L70

/close
