### ISSUE TITLE
Monitor bloat data

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1438]
**Is your feature request related to a problem? Please describe.**

It would be nice to monitor bload data, at least once a week.

https://raw.githubusercontent.com/pgexperts/pgx_scripts/master/bloat/table_bloat_check.sql

**Comment by pacospace** [comment]
do we want to simply run .sql file once week? Do we wan to create query in storages running raw sql statements that we could check from an endpoint in management-API maybe? WDYT @fridex?

**Comment by fridex** [comment]
> do we want to simply run .sql file once per week? Do we wan to create query in storages running raw sql statements that we could check from an endpoint in management-API maybe? WDYT @fridex?

IMHO I would put that raw SQL statement to metrics-exporter - its related to metrics. WDYT?

**Comment by pacospace** [comment]
So creating some query in storages that can be run from metrics-exporter with a time period that can be parametrized (e.g. one week)?

**Comment by fridex** [comment]
> So creating some query in storages that can be run from metrics-exporter with a time period that can be parametrized (e.g. one week)?

Sounds good to me :+1: The query will need to live in thoth-storage library anyway.

From the metrics-exporter point of view - I would like to keep metrics-exporter stateless. Would it be possible to keep the last update timestamp on the Prometheus side somehow?

**Comment by pacospace** [comment]
It should possible yes. We could check last time metric has been updated on Prometheus side and when the time period we want has passed, update that value. WDYT?

**Comment by fridex** [comment]
> It should possible yes. We could check last time metric has been updated on Prometheus side and when the time period we want has passed, update that value. WDYT?

+1 on my side :+1:
