### ISSUE TITLE
Use different name for postgres database

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1439]
**Is your feature request related to a problem? Please describe.**

We should use a different name for PG database, its not a good practice to use the default one - `postgres`.

**Comment by pacospace** [comment]
We are already using a different name right @harshad16 ? can we close the issue?

**Comment by harshad16** [comment]
yes, we have named it `thoth` :+1:

**Comment by pacospace** [comment]
> yes, we have named it `thoth`

Nice name :D
