### ISSUE TITLE
Advised software stacks are not synced

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1459]
**Describe the bug**

It looks like advised software stacks are not synced into the knowledge graph.

**To Reproduce**
1. Go to Grafana dashboards
2. Check number of advised software stacks
3. Check debug messages printed by graph-sync: `2020-01-08 14:51:13,828 [1] WARNING  thoth.storages.graph.postgres:4801: Omitting stack as no output Pipfile.lock was provided`

**Comment by pacospace** [comment]
Can we close this issue @fridex? :)
