### ISSUE TITLE
Use index when querying software environment for symbols

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1570]
**Is your feature request related to a problem? Please describe.**

It looks like `get_analyzed_image_symbols_all` query does not use indexes that should be created for `os_name`, `os_version`, `python_version` and `cuda_version`. This leads to ineffective sequential scan.

**Describe the solution you'd like**

The related index should be installed.

**Describe alternatives you've considered**

-

**Additional context**

https://github.com/thoth-station/storages/pull/1569

**Comment by KPostOffice** [comment]
I think this can be closed?
