### ISSUE TITLE
Check found Python interpreter when obtaining package symbols

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1573]
**Describe the bug**

The current logic behind the container image symbols query takes into account Python version. Unfortunatelly, this value is always `null` in our database:

https://github.com/thoth-station/storages/blob/937f65356c5f6f022e0da87be3d67c1c07c45f52/thoth/storages/graph/postgres.py#L3985-L3987

**To Reproduce**
1. Run container image analysis
2. Wait container image analysis results to be synced
3. Check synced results and see `python_version` column
4. See `null` value

**Expected behavior**

We should be able to query for Python version when obtaining package symbols in the given software environment.

**Additional context**

As the symbols query on adviser side expects our software environments (not the ones being analyzed from external sources), we can explicitly provide Python version based on container image name we analyze (this is a special case for "SoftwareEnvironment", cannot be generalized for "ExternalSoftwareEnvironment"). This can be parsed from container image name as we have a naming convention for them, such as `quay.io/thoth-station/s2i-thoth-ubi8-py36` (`3.6` in this case).

If the container image name fails to be parsed, the sync should not happen (the transaction will be rolled back).

**Comment by KPostOffice** [comment]
Is it OK to assume that the name will always look like ...-...-...-pyXX?

**Comment by fridex** [comment]
> Is it OK to assume that the name will always look like ...-...-...-pyXX?

Yes, that's our naming convention.
