### ISSUE TITLE
Sort columns in performance indicators

### ISSUE THREAD

**Issue by CermakM** [thoth-station/storages#1607]
The current sorting is as follows:

<table style="border-collapse:collapse">
<tr><th>origin</th><th>version</th><th>overall_score</th><th>exit_code</th><th>ru_utime</th><th>ru_stime</th><th>ru_maxrss</th><th>ru_ixrss</th><th>ru_idrss</th><th>ru_isrss</th><th>ru_minflt</th><th>ru_majflt</th><th>ru_nswap</th><th>ru_inblock</th><th>ru_oublock</th><th>ru_msgsnd</th><th>ru_msgrcv</th><th>ru_nsignals</th><th>ru_nvcsw</th><th>ru_nivcsw</th><th>id</th><th>inspection_run_id</th><th>device</th><th>matrix_size</th><th>dtype</th><th>reps</th><th>elapsed</th><th>rate</th><th>component</th></tr>
</table>

It would be easier to read if columns that are common to all PIs would be at the end of the table and PK and FK at the beginning.

**Comment by fridex** [comment]
I'm about to close this. I think it is referring to relative column placement in the database/pgweb. pgweb is not used as our data exploratory component (it is not deployed in stage/prod environments). We show the data in notebooks where they are filtered or additionally combined/adjusted.

Thanks for the idea though.
