### ISSUE TITLE
PythonSoftwareStack table has three records!!

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#1675]
**Describe the bug**
`PythonSoftwareStack` currently has three columns: `software_stack_type`, `performance_score` and `overall_score`. This table is linked to `PythonRequirementsLocked` and `ExternalPythonRequirementsLocked` which are respectively linked to `PythonPackageVersion` and `PythonPackageVersionEntity`. Every service that sync a software stack (Adviser, Amun, etc..) is currently referring to the same record in `PythonSoftwareStack`. This cause an issue if we want to retrieve the software stack used by a User or suggested by Adviser querying the database because there is no unique `PythonSoftwareStack` record created each time.

**To Reproduce**
1. Go to PythonSoftwareStack table in the database. There are only three entries.
Other way is to create a query to retrieve python package version or python package version entities for a specific python software stack (PythonSoftwareStack table).

**Expected behavior**
Every packages in a software stacks is identified by a unique software stack id. One solution could be to create a unique hash and add this column to PythonSoftwareStack, and only modify the method https://github.com/thoth-station/storages/blob/d1bc3db14fe50647f08606c50940f876ed665134/thoth/storages/graph/postgres.py#L3560.

```
from
        software_stack, _ = PythonSoftwareStack.get_or_create(
            session,
            performance_score=performance_score,
            overall_score=overall_score,
            software_stack_type=software_stack_type,
        )
to
        software_stack, _ = PythonSoftwareStack.get_or_create(
            session,
            `hash=_create_unique_hash(requirements_lock=requirements_lock)`
            performance_score=performance_score,
            overall_score=overall_score,
            software_stack_type=software_stack_type,
        )
```
with new method to create the hash.

**Comment by fridex** [comment]
> ```
> from
>         software_stack, _ = PythonSoftwareStack.get_or_create(
>             session,
>             performance_score=performance_score,
>             overall_score=overall_score,
>             software_stack_type=software_stack_type,
>         )
> to
>         software_stack, _ = PythonSoftwareStack.get_or_create(
>             session,
>             `hash=_create_unique_hash(requirements_lock=requirements_lock)`
>             performance_score=performance_score,
>             overall_score=overall_score,
>             software_stack_type=software_stack_type,
>         )
> ```


Other solutions as discussed on the call:

 1. add columns referring `PythonRequirementsLocked.id`, `ExternalPythonRequirementsLocked.id`, and `PythonRequirements.id` to the `PythonSoftwareStack` table - this need to be verified if possible as there is "chicken-egg" problem with the linked tables (should be possible as it is part of one transaction)

2. remove `PythonSoftwareStack.id` from `PythonRequirementsLocked`, `ExternalPythonRequirementsLocked` and `PythonRequirements`. In that case, `PythonSoftwareStack rec`ord will be created after `PythonRequirementsLocked`, `ExternalPythonRequirementsLocked` and `PythonRequirements` records. Verification is needed to check if we can do it from semantics point of view (we do not lose some linkage).

**Comment by pacospace** [comment]
> > ```
> > from
> >         software_stack, _ = PythonSoftwareStack.get_or_create(
> >             session,
> >             performance_score=performance_score,
> >             overall_score=overall_score,
> >             software_stack_type=software_stack_type,
> >         )
> > to
> >         software_stack, _ = PythonSoftwareStack.get_or_create(
> >             session,
> >             `hash=_create_unique_hash(requirements_lock=requirements_lock)`
> >             performance_score=performance_score,
> >             overall_score=overall_score,
> >             software_stack_type=software_stack_type,
> >         )
> > ```
> 
> Other solutions as discussed on the call:
> 
> 1. add columns referring `PythonRequirementsLocked.id`, `ExternalPythonRequirementsLocked.id`, and `PythonRequirements.id` to the `PythonSoftwareStack` table - this need to be verified if possible as there is "chicken-egg" problem with the linked tables (should be possible as it is part of one transaction)
> 2. remove `PythonSoftwareStack.id` from `PythonRequirementsLocked`, `ExternalPythonRequirementsLocked` and `PythonRequirements`. In that case, `PythonSoftwareStack rec`ord will be created after `PythonRequirementsLocked`, `ExternalPythonRequirementsLocked` and `PythonRequirements` records. Verification is needed to check if we can do it from semantics point of view (we do not lose some linkage).

But in this way we would have many `PythonSoftwareStack` created for each `PythonRequirementsLocked`, `ExternalPythonRequirementsLocked` as they are created for each `PythonPackageVersion` or `PythonpackageVersionEntity` respectively.
