### ISSUE TITLE
[1pt] Adding Source Type to adviser_run table 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/storages#1854]
- [x] - Add `source_type` column to adviser_run table. 
- [x] - Update alembic head. 
- [x] - Add to attribute in [sync_adviser_result](https://github.com/thoth-station/storages/blob/1dd801548a937859311fe743df1beb22fd5a2d48/thoth/storages/graph/postgres.py#L4924) method 
- [x] - Create a new release 

cc - @pacospace  :smile:

**Comment by pacospace** [comment]
:fireworks:

**Comment by pacospace** [comment]
This will allow us to have SLI on the usage of each Thoth integration @goern

**Comment by saisankargochhayat** [comment]
Added in #1862
