### ISSUE TITLE
Installation Requirement

### ISSUE THREAD

**Issue by GiorgosKarantonis** [thoth-station/storages#1858]
Podman has to be already installed from https://podman.io/getting-started/installation.html in order to run PostgreSQL locally.

**Comment by saisankargochhayat** [comment]
> Podman has to be already installed from https://podman.io/getting-started/installation.html in order to run PostgreSQL locally.

Do you want this to be included in the readme? Or what is the issue?

**Comment by GiorgosKarantonis** [comment]
I think it would be better to have it in the readme

**Comment by fridex** [comment]
I tried to document running pg locally in the README file:

https://github.com/thoth-station/storages#running-postgresql-locally

All the needed packages can be installed using dnf/pip:

```console
dnf install -y podman podman-compose
# or docker-compose from pip [1]
# pip install podman-compose
```

If you have some troubles running commands, please let us know. Also, feel free to extend the README file in a PR if needed.

[1] https://pypi.org/project/podman-compose
