### ISSUE TITLE
pypi.python.org is pypi.org

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#1871]
**Describe the bug**

Some stack configurations use pypi.python.org as a source of packages. This old URL redirects to pypi.org. We should add capability to automatically remap all the index URLs pointing to legacy pypi.python.org to pypi.org.

As of now, we maintain both entries as separate Python package indexes. This, in fact, doubles the number of packages stored.

**Expected behavior**

Remap all pypi.python.org URLs to pypi.org.

This change should go also to thoth-python.

**Comment by saisankargochhayat** [comment]
From the schema, it seems `PythonPackageVersionEntity`, `PythonPackageVersion`, `PythonPackageRequirement`, depends on `PythonPackageIndex`.

**Comment by goern** [comment]
is this still valid?

**Comment by fridex** [comment]
> is this still valid?

Not anymore.
