### ISSUE TITLE
Create a query to fetch all packages, that have been solved, but SI hasn't been run on it. 

### ISSUE THREAD

**Issue by saisankargochhayat** [thoth-station/storages#1947]
_Originally posted by @fridex in https://github.com/thoth-station/graph-refresh-job/issues/457#issuecomment-676128893_
Create and query in storages, that would look for all solved packages, and check if they exist in `si_aggregated_run` table and if it doesn't exist there, we should produce messages to schedule SI workflows.
- [ ] The table in which we have details of all the solved packages - 
- [ ] The SI table to check against is -

**Comment by pacospace** [comment]
> _Originally posted by @fridex in [thoth-station/graph-refresh-job#457 (comment)](https://github.com/thoth-station/graph-refresh-job/issues/457#issuecomment-676128893)_
> Create and query in storages, that would look for all solved packages, and check if they exist in `si_aggregated_run` table and if it doesn't exist there, we should produce messages to schedule SI workflows.
> 
> * [ ]  The table in which we have details of all the solved packages -

`PythonPackageVersion` is the table that is populated by solvers once a new package, version, index for a certain solver has been solved.

> * [ ]  The SI table to check against is -

`SecurityIndicatorAggregatedRun` contains all knowledge about security after security-indicator workflows have been run. 

To find out which packages are solved but not analyzed from Security Point of view, there should be a combination of two queries at the moment:

1. `get_solved_python_package_versions_all` (https://github.com/thoth-station/storages/blob/25671755fc23bb13e8448ca1e7b71bcff7ebd240/thoth/storages/graph/postgres.py#L918) that would give back: 
```
        >>> from thoth.storages import GraphDatabase
        >>> graph = GraphDatabase()
        >>> graph.get_solved_python_package_versions_all()
        [('regex', '2018.11.7', 'https://pypi.org/simple'), ('tensorflow', '1.11.0', 'https://pypi.org/simple')]
```

2. Once solved packages are retrieves,. the other query for each package, version, index that should be used is `si_aggregated_python_package_version_exists` https://github.com/thoth-station/storages/blob/25671755fc23bb13e8448ca1e7b71bcff7ebd240/thoth/storages/graph/postgres.py#L2203. In this way it is possible to check if SI information exist about that package, version, index.

**Comment by fridex** [comment]
Just one minor comment here - you don't need to do 2 queries but you can construct all of this in a single database query using sqlalchemy. It should be faster as there is reduced serialization, network overhead and database can do the job for which it is optimized. You can check already existing query for the unsolved packages where similar diff is done to `python_package_version_entity` and `python_package_version` tables (you switch `python_package_version_entity` to the si specific table in your case).

**Comment by saisankargochhayat** [comment]
Thanks! I will try the same.
