### ISSUE TITLE
Mark unsolvable packages in the graph database

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#195]
We should have an ability to mark certain packages in the graph database as unsolvable. They are insolvable if solver cannot solve them (e.g. the given version does not exist, the package does not exist on the given index). This way we will prevent graph-refresh-job from scheduling same packages over and over again.

**Comment by fridex** [comment]
BTW we should have an ability from API server to reschedule solvers for such packages (e.g. we added a new index into thoth's configuration).

**Comment by fridex** [comment]
Done in #205.

**Comment by goern** [comment]
added https://trello.com/c/haNQqlEK to be groomed
