### ISSUE TITLE
Extend kebechet github installation table with managers and time for Internal Trigger feature [3pt]

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#2016]
As Thoth.

I would like to provide my services to users of Kebechet and keep track of what managers are used by users so that we can prioritize future Kebechet features and provide Kebechet services faster.

- [x] Extend kebechet_github_installation table to have one column per manager, with boolean set to False by default and datetime/timestamp optional.
- [x] Create migration.
- [x] Create new method to query for current state of managers used by user

References:
- https://github.com/thoth-station/kebechet/issues/571

**Comment by saisankargochhayat** [comment]
So we have added the changes to the schema and also added the query method, do we want anything else for this issue? @pacospace

**Comment by pacospace** [comment]
I think for this part we are good!! Thanks!! Now we need to review the storages schema to add the software stack ID!

**Comment by pacospace** [comment]
https://github.com/thoth-station/storages/issues/2038

**Comment by saisankargochhayat** [comment]
Closed with #2024 #2035
