### ISSUE TITLE
Make schema update an async task

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2080]
**Is your feature request related to a problem? Please describe.**

As our database grows pretty significantly, some schema updates take too much time to be handled in a synchronous call we have on management-api. We should move the schema update logic into a one-time job that is run to make sure the database is updated and up2date.

**Describe the solution you'd like**

Create a simple one-time job that will update the database schema. This job can be subsequently used by an operator to make sure the deployment is correctly updated and all the components requiring the new schema can be updated.

**Additional context**

See https://github.com/thoth-station/thoth-application/issues/610 that is tightly associated with this issue.

Over time this should become part of an operator that updates deployment.

**Comment by fridex** [comment]
CC @pacospace

**Comment by pacospace** [comment]
> CC @pacospace

Thanks @fridex.

WDYT? https://github.com/thoth-station/workflow-helpers/pull/168

We can have a workflow (graph-update-schema) that can be triggered by management API?

**Comment by pacospace** [comment]
> > CC @pacospace
> 
> Thanks @fridex.
> 
> WDYT? [thoth-station/workflow-helpers#168](https://github.com/thoth-station/workflow-helpers/pull/168)
> 
> We can have a workflow (graph-update-schema) that can be triggered by management API from thoth Team? basically changing the logic of the current endpoint to do async update.

Or should we create a new repo `graph-update-schema` that perform that task?

**Comment by fridex** [comment]
The workflow helpers approach looks like more fancy solution (less maintenance). The update could be also done using thoth-storages CLI but that would require turning this repo into a component. I think the workflow helpers is the most straightforward solution now. :+1:

**Comment by pacospace** [comment]
> The workflow helpers approach looks like more fancy solution (less maintenance). The update could be also done using thoth-storages CLI but that would require turning this repo into a component. I think the workflow helpers is the most straightforward solution now.

Then we can proceed:

- [ ] new workflow task method (https://github.com/thoth-station/workflow-helpers/pull/168)
- [ ] new workflow in thoth-application
- [ ] new method in thoth-common
- [ ] add logic to management-API to submit that workflow ( in frontend?)

and leave this issue for future improvements.

WDYT?

**Comment by fridex** [comment]
> > The workflow helpers approach looks like more fancy solution (less maintenance). The update could be also done using thoth-storages CLI but that would require turning this repo into a component. I think the workflow helpers is the most straightforward solution now.
> 
> Then we can proceed:
> 
> * [ ]  new workflow task method ([thoth-station/workflow-helpers#168](https://github.com/thoth-station/workflow-helpers/pull/168))
> * [ ]  new workflow in thoth-application
> * [ ]  new method in thoth-common to schedule that workflow
> * [ ]  add logic to management-API to submit that workflow ( in frontend?)
> 
> and leave this issue for future improvements.
> 
> WDYT?

If we place it in the frontend namespace, will it require argo workflows (controller, ui and other required objects) being deployed into frontend namespace?

**Comment by pacospace** [comment]
> > > The workflow helpers approach looks like more fancy solution (less maintenance). The update could be also done using thoth-storages CLI but that would require turning this repo into a component. I think the workflow helpers is the most straightforward solution now.
> > 
> > 
> > Then we can proceed:
> > 
> > * [ ]   new workflow task method ([thoth-station/workflow-helpers#168](https://github.com/thoth-station/workflow-helpers/pull/168))
> > * [ ]   new workflow in thoth-application
> > * [ ]   new method in thoth-common to schedule that workflow
> > * [ ]   add logic to management-API to submit that workflow ( in frontend?)
> > 
> > and leave this issue for future improvements.
> > WDYT?
> 
> If we place it in the frontend namespace, will it require argo workflows (controller, ui and other required objects) being deployed into frontend namespace?

Right, we cannot schedule cross namespaces, then middletier? like solver (so management api does not need access to other namespaces)?

**Comment by pacospace** [comment]
> > > > The workflow helpers approach looks like more fancy solution (less maintenance). The update could be also done using thoth-storages CLI but that would require turning this repo into a component. I think the workflow helpers is the most straightforward solution now.
> > > 
> > > 
> > > Then we can proceed:
> > > 
> > > * [ ]    new workflow task method ([thoth-station/workflow-helpers#168](https://github.com/thoth-station/workflow-helpers/pull/168))
> > > * [ ]    new workflow in thoth-application
> > > * [ ]    new method in thoth-common to schedule that workflow
> > > * [ ]    add logic to management-API to submit that workflow ( in frontend?)
> > > 
> > > and leave this issue for future improvements.
> > > WDYT?
> > 
> > 
> > If we place it in the frontend namespace, will it require argo workflows (controller, ui and other required objects) being deployed into frontend namespace?
> 
> Right, we cannot schedule cross namespaces, then middletier? like solver (so management api does not need access to other namespaces)?

Actually management-API should become also a kafka producer and investigator should schedule actual workflows, but that would require more work respect to this feature. WDYT?

**Comment by fridex** [comment]
> Actually management-API should become also a kafka producer and investigator should schedule actual workflows, but that would require more work respect to this feature. WDYT?

Given this fact and also given the long-term solution (using operators) what about scheduling just a job in infra namespace? We will need to rework this anyway, so... :innocent:

**Comment by pacospace** [comment]
> > Actually management-API should become also a kafka producer and investigator should schedule actual workflows, but that would require more work respect to this feature. WDYT?
> 
> Given this fact and also given the long-term solution (using operators) what about scheduling just a job in infra namespace? We will need to rework this anyway, so...

We can also simply have a workflow template that be scheduled with `argo submit` directly to speed up :)

**Comment by fridex** [comment]
It might go against the "argo-cd has access to namespace" rule - no human interaction in namespaces :)

**Comment by pacospace** [comment]
> It might go against the "argo-cd has access to namespace" rule - no human interaction in namespaces :)

:robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: :robot: right, we can still use the workflow-herlpers image right?

**Comment by fridex** [comment]
Sure :+1:

**Comment by pacospace** [comment]
> Sure

Thanks! https://github.com/thoth-station/workflow-helpers/pull/168

**Comment by pacospace** [comment]
Do we want to substitute the method in management API with the new async task?

**Comment by fridex** [comment]
> Do we want to substitute the method in management API with the new async task?

Yes, I think that's required here.

**Comment by pacospace** [comment]
Sounds good, after this is merged: https://github.com/thoth-station/common/pull/1083 we can release new thoth-common :)
