### ISSUE TITLE
Does this repo need `.aicoe-ci.yaml`?

### ISSUE THREAD

**Issue by bissenbay** [thoth-station/storages#2122]
Related-To: https://github.com/thoth-station/thoth-application/issues/545#issuecomment-735908736

**Comment by harshad16** [comment]
please follow this comment: https://github.com/thoth-station/analyzer/issues/292#issuecomment-736007922

**Comment by bissenbay** [comment]
`.aicoe-ci.yaml` was added with this PR: https://github.com/thoth-station/storages/pull/2121
