### ISSUE TITLE
Manager fields in kebechet_github_installations all False

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/storages#2135]
**Describe the bug**
When inspecting table `kebechet_github_installations`, I have noticed that all of the manager fields are set to `False`.

**To Reproduce**
I have also tried e.g. the function
```
graph.get_kebechet_github_installations_active_managers(slug="thoth-station/mi"`)
```
where as expected (according to fields), nothing was returned (e.g. the `update_manager` and others should have been returned).

The dump I am using is  `pg_dump-20-12-03-00-02-14` .

**Expected behavior**
Correct booelan values for present managers according to the repository.

**Screenshots**
![image](https://user-images.githubusercontent.com/46632404/101119422-9b0f7400-35eb-11eb-9c53-7b66a1482df4.png)

**Comment by pacospace** [comment]
> **Describe the bug**
> When inspecting table `kebechet_github_installations`, I have noticed that all of the manager fields are set to `False`.
> 
> **To Reproduce**
> I have also tried e.g. the function
> 
> ```
> graph.get_kebechet_github_installations_active_managers(slug="thoth-station/mi"`)
> ```
> 
> where as expected (according to fields), nothing was returned (e.g. the `update_manager` and others should have been returned).
> 
> The dump I am using is `pg_dump-20-12-03-00-02-14` .
> 
> **Expected behavior**
> Correct booelan values for present managers according to the repository.
> 
> **Screenshots**
> ![image](https://user-images.githubusercontent.com/46632404/101119422-9b0f7400-35eb-11eb-9c53-7b66a1482df4.png)

Thanks @xtuchyna :) It's not a bug of thoth-storages. The logic is there already and when we modify schema by default we put all false, they will be updated in the next round by Kebechet, we need to add that in User-API :)
