### ISSUE TITLE
Optimize get_python_package_version_platform_all

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2181]
**Describe the bug**

See the query in:

https://github.com/thoth-station/storages/blob/483d04dca2246582b5397c8698896e6541790c50/thoth/storages/graph/postgres.py#L2256-L2261

**To Reproduce**
1. Use the query against a large database
2. See the performance issue

**Expected behavior**

The query should be more optimal, it does not need to go through all DependsOn entries.

**Comment by fridex** [comment]
Looks like index on `platform` does not solve this as a sequential scan is performed. Creating a database view does not work in this case, as postgres does not optimize table views. Looks like we will need to make an enum out of platform.

**Comment by goern** [comment]
@pacospace whats happening?
/lifecycle frozen

**Comment by goern** [comment]
@pacospace you are working on this, right?

/lifecycle active

**Comment by pacospace** [comment]
> @pacospace you are working on this, right?
> 
> /lifecycle active

@goern 
The PR to close it is ready, tested and linked here: https://github.com/thoth-station/storages/pull/2354
