### ISSUE TITLE
Missing solver-ubi-8-py38 in database Ecosystem Solver table

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#2196]
**Describe the bug**
Missing solver-ubi-8-py38 in database but there is Missing solver-rhel-8-py38 in database. When querying for data in the database for specific solver solver-ubi-8-py38, none are identified. This might affect queries for adviser to look for data for rhel-8 mapped to ubi-8

**To Reproduce**
1. Have a look at the database

**Expected behavior**
In Ecosystem solver table we should find `solver-ubi-8-py38`

**Screenshots**

**Additional context**

**Comment by pacospace** [comment]
I think it does affect queries, as we map to ubi always if someone input rhel. cc @fridex

**Comment by goern** [comment]
@pacospace is this still relevant, if not please close it

**Comment by goern** [comment]
is `curl -X GET "https://management.moc.thoth-station.ninja/api/v1/solvers" -H  "accept: application/json"` a valid test for this? is this covered by an integration test?

**Comment by pacospace** [comment]
> is `curl -X GET "https://management.moc.thoth-station.ninja/api/v1/solvers" -H "accept: application/json"` a valid test for this? is this covered by an integration test?

This is an inconsistency in data in the database, not from solver CM. If the map from rhel 8 to ubi 8 is used in every method, we can close this issue.

**Comment by goern** [comment]
sounds like a query we can run against the database, so that we check for consistency?

**Comment by pacospace** [comment]
> sounds like a query we can run against the database, so that we check for consistency?

We have already that actually, number of solver in CM vs number of solver in database and we also planned an alarm there. So we can close this issue.

**Comment by fridex** [comment]
If I recall correctly, we had `rhel` in the database that should not happen as it should be mapped to `ubi`. If `rhel` entries will be kept in the database, they will not cause any issues on the user side (as there is no solver installed). The incosystency will arise in monitoring when metrics-exporter exposes info about them. This might be confusing as we do not have "`rhel`" solvers per say. So the solution to this issue:

* make sure we map solver names correctly - https://github.com/thoth-station/storages/issues/2199
* check if we have `rhel` entries in the database -- if so, we can remove these entries using the purge-job

@pacospace could you please verify we have only `ubi` solvers reported in deployments and no `rhel` solvers?

**Comment by pacospace** [comment]
> If I recall correctly, we had `rhel` in the database that should not happen as it should be mapped to `ubi`. If `rhel` entries will be kept in the database, they will not cause any issues on the user side (as there is no solver installed). The incosystency will arise in monitoring when metrics-exporter exposes info about them. This might be confusing as we do not have "`rhel`" solvers per say. So the solution to this issue:
> 
> * make sure we map solver names correctly - #2199
> * check if we have `rhel` entries in the database -- if so, we can remove these entries using the purge-job
> 
> @pacospace could you please verify we have only `ubi` solvers reported in deployments and no `rhel` solvers?

@fridex from Grafana in prod, it seems to show 8 different solvers
![Screenshot from 2021-06-11 13-40-51](https://user-images.githubusercontent.com/27498679/121681163-c2735c00-caba-11eb-9992-775455fa1d5e.png)

**Comment by pacospace** [comment]
> If I recall correctly, we had `rhel` in the database that should not happen as it should be mapped to `ubi`. If `rhel` entries will be kept in the database, they will not cause any issues on the user side (as there is no solver installed). The incosystency will arise in monitoring when metrics-exporter exposes info about them. This might be confusing as we do not have "`rhel`" solvers per say. So the solution to this issue:
> 
> * make sure we map solver names correctly - #2199
> * check if we have `rhel` entries in the database -- if so, we can remove these entries using the purge-job
> 
> @pacospace could you please verify we have only `ubi` solvers reported in deployments and no `rhel` solvers?

We actually map `ubi` to `rhel` in the database. So it will be synced as `rhel`: https://github.com/thoth-station/common/blob/826ad8f1db5234d2003f21d66b8ec0f6a29d2cea/thoth/common/helpers.py#L182

**Comment by pacospace** [comment]
> > If I recall correctly, we had `rhel` in the database that should not happen as it should be mapped to `ubi`. If `rhel` entries will be kept in the database, they will not cause any issues on the user side (as there is no solver installed). The incosystency will arise in monitoring when metrics-exporter exposes info about them. This might be confusing as we do not have "`rhel`" solvers per say. So the solution to this issue:
> > 
> > * make sure we map solver names correctly - #2199
> > * check if we have `rhel` entries in the database -- if so, we can remove these entries using the purge-job
> > 
> > @pacospace could you please verify we have only `ubi` solvers reported in deployments and no `rhel` solvers?
> 
> We actually map `ubi` to `rhel` in the database. So it will be synced as `rhel`: https://github.com/thoth-station/common/blob/826ad8f1db5234d2003f21d66b8ec0f6a29d2cea/thoth/common/helpers.py#L182
> 
> I will check syncing logic and verify the potential issue

- EcosystemSolver table is synced only by solver!
- We can delete with purge job all solvers in EcosystemSolver Table that have rhel and fedora basically.
- Adjust logic of solver sync, to use always document name and no mapping from ubi to rhel.

@fridex when you have a moment let's talk about this, because I have some questions on the mapping. Thanks!

**Comment by fridex** [comment]
> @fridex from Grafana in prod, it seems to show 8 different solver_name from EcosystemSolver table

That means the prod deployment is not configured correctly. Number of solvers stated in the configmap should match number of entries in the EcosystemSolver table. Otherwise an alarm should be triggered (I think we had an issue for that).

The question now is what are these 8 entries? Are they consistent with respect to ubi/rhel naming?

> * EcosystemSolver table is synced only by solver!

That sounds correct. We will need to make sure it is properly removed on purge (I do not remember if I've done so).

> * We can delete with purge job all solvers in EcosystemSolver Table that have rhel and fedora basically.

What would solve this?

> * Adjust logic of solver sync, to use always document name and no mapping from ubi to rhel.

We introduced mapping as `ubi` and `rhel` are ABI compatible - see https://thoth-station.ninja/j/rhel_ubi.html

> @fridex when you have a moment let's talk about this, because I have some questions on the mapping. Thanks!

Let's keep the discussion here so that steps and approaches are documented. Thanks!

**Comment by pacospace** [comment]
> > @fridex from Grafana in prod, it seems to show 8 different solver_name from EcosystemSolver table
> 
> That means the prod deployment is not configured correctly. Number of solvers stated in the configmap should match number of entries in the EcosystemSolver table. Otherwise an alarm should be triggered (I think we had an issue for that).
> 
> The question now is what are these 8 entries? Are they consistent with respect to ubi/rhel naming?
> 
> > * EcosystemSolver table is synced only by solver!
> 
> That sounds correct. We will need to make sure it is properly removed on purge (I do not remember if I've done so).
> 
> > * We can delete with purge job all solvers in EcosystemSolver Table that have rhel and fedora basically.
> 
> What would solve this?
> 
> > * Adjust logic of solver sync, to use always document name and no mapping from ubi to rhel.
> 
> We introduced mapping as `ubi` and `rhel` are ABI compatible - see https://thoth-station.ninja/j/rhel_ubi.html
> 
> > @fridex when you have a moment let's talk about this, because I have some questions on the mapping. Thanks!
> 
> Let's keep the discussion here so that steps and approaches are documented. Thanks!

Sure!

So I ll address the issues one by one

- storages: [ ] https://github.com/thoth-station/storages/blob/cb118707ab6cbdf529bfd346c6d3040118f9b8a0/thoth/storages/graph/postgres.py#L5094

**Comment by fridex** [comment]
> > We actually map `ubi` to `rhel` in the database. So it will be synced as `rhel`: https://github.com/thoth-station/common/blob/826ad8f1db5234d2003f21d66b8ec0f6a29d2cea/thoth/common/helpers.py#L182
> > I will check syncing logic and verify the potential issue

Based on this, we should not have `os_name=ubi` in the database. However, stage and prod keep following entries:

![Screenshot_2021-06-11_16-47-12](https://user-images.githubusercontent.com/880687/121705449-ee034000-cad4-11eb-8dc3-568b5babf3f3.png)

I will delete them as they are not consistent with the mapping. Also the ecosystem solver table should not keep any `ubi` entries (as they should be mapped to `rhel` as well). Checking stage and prod deployment, I can see one UBI entry:

![Screenshot_2021-06-11_16-50-19](https://user-images.githubusercontent.com/880687/121705780-476b6f00-cad5-11eb-8740-3696cbd76502.png)

This one should be also deleted. With this, number of solvers reported from prod deployment should decrease to 7. I will delete these entries from stage and prod database, ACK?

**Comment by fridex** [comment]
> I will delete these entries from stage and prod database, ACK?

Deleted based on 👍🏻 on the comment. Could you please verify number of solvers reported in stage/prod? thanks!

**Comment by pacospace** [comment]
> > I will delete these entries from stage and prod database, ACK?
> 
> Deleted based on 👍🏻 on the comment. Could you please verify number of solvers reported in stage/prod? thanks!

stage
![Screenshot from 2021-06-11 18-22-58](https://user-images.githubusercontent.com/27498679/121718238-63294200-cae2-11eb-9498-a263fcb1ebf9.png)
EcosystemSolver Table
`solver-fedora-31-py37`, `solver-fedora-31-py38`, `solver-fedora-32-py36`, `solver-fedora-32-py37`, `solver-fedora-32-py38`, `solver-rhel-8-py36`, `solver-rhel-8-py38`

prod
![Screenshot from 2021-06-11 13-40-51](https://user-images.githubusercontent.com/27498679/121718444-9e2b7580-cae2-11eb-85f7-a9b7b3cdead1.png)

**Comment by fridex** [comment]
Looks good, except for prod. We should purge old solvers and install new. These fedora ones are EOL anyway.

**Comment by pacospace** [comment]
> Looks good, except for prod. We should purge old solvers and install new ones. These fedora ones are EOL anyway.

Should we just retrigger purge job in prod?

I closed https://github.com/thoth-station/storages/pull/2345 as we do not need a change in logic syncing to EcosystemSolver which correctly syncs rhel.

But we need to check also the sync is correctly done on SoftwareEnvironment Tables and other tables that consider os_name when syncing, the same mapping should be applied right?

**Comment by fridex** [comment]
> > Looks good, except for prod. We should purge old solvers and install new ones. These fedora ones are EOL anyway.
> 
> Should we just retrigger purge job in prod?

This is planned for the release - @harshad16 works on this.

> But we need to check also the sync is correctly done on SoftwareEnvironment Tables and other tables that consider os_name when syncing, the same mapping should be applied right?

I think we can keep these entries for now as they do not create any preassure on the database.

/close
