### ISSUE TITLE
Revisit operating system name entries in the database

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2199]
**Describe the bug**

Following the discussion in https://github.com/thoth-station/storages/pull/2197, a bug discovered in https://github.com/thoth-station/storages/issues/2196 and the discussion on our meeting, we should have a look at operating system name entries in the database. Specifically, make sure rhel/ubi are treated as synonyms where it is appropriate (solver runs but not container image analyses).

**Comment by goern** [comment]
@fridex is this still a thing?

**Comment by fridex** [comment]
Yes.

/remove-lifecycle stale

**Comment by pacospace** [comment]
I think we can close this issue with https://github.com/thoth-station/storages/pull/2351, feel free to reopen it if required!
