### ISSUE TITLE
Make platform constant in sources

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2374]
**Is your feature request related to a problem? Please describe.**

With recent issues discovered on the database side (thanks to @harshad16), we could make platform constant - as we do not plan to support other platforms in near future, having just linux-86_64 should work fine. It will reduce pressure on the database queries and will save few gigs of disk space given the size of tables (`depends_on`).

**Describe the solution you'd like**

Do not store platform in `depends_on` table, but rather make it constant (`linux-x86_64`) in sources.

**Comment by pacospace** [comment]
@harshad16 already solved this issue, I think it can be closed!

**Comment by pacospace** [comment]
Let's close it, feel to reopen :)
