### ISSUE TITLE
Deleting entries still in use

### ISSUE THREAD

**Issue by KPostOffice** [thoth-station/storages#2385]
**Describe the bug**
In the database, we use `get_or_create` when adding entries to the database.  This is to keep us from duplicating entries and instead we are able to reuse references to certain software stacks, runtime environments, etc.  However, most of the entries in our database cascade on deletion. This does not take into account that what is being deleted may be referenced more than once.  Cascading seems like a bad practice with our method of entry creation.

**To Reproduce**
Create two adviser runs with the same software stack. If you delete one, the other's link to the software stack becomes broken.

https://github.com/thoth-station/storages/blob/ecbfa89751292d7e16a360235b8dab63fbbb40d3/thoth/storages/graph/models.py#L531
**Expected behavior**
Deletion of foreign table entries should happen only when there are no other entries referring to them.  This can be done by either cleaning with a cronjob or conditionally checking if the entry should be deleted.

**Additional context**
As far as I've read, `cascade` doesn't handle one child to many parents relationship, please comment if you know differently.

**Comment by KPostOffice** [comment]
@pacospace I tested this by creating and deleting KebechetGithubAppInstallations with the same python stack and environment then deleting one of the two installations. The associated stack and environment were not deleted, however, they also were not deleted when I removed both entries. It is possible that there are zombie entries for the python stack and the environment which are waiting to be revived when a new entry with the same environment/software stack is needed.

**Comment by KPostOffice** [comment]
I think this can be closed. We won't delete entries which are still in use, but what can happen is that some data can stick around even if it's not associated with anything anymore. `cascade` occurs in the opposite direction from what I assumed

**Comment by fridex** [comment]
OK, so let's close this one. Thanks @KPostOffice.

/close
