### ISSUE TITLE
Add simple example on using thoth handler for data on Ceph in the README

### ISSUE THREAD

**Issue by pacospace** [thoth-station/storages#2390]
**Is your feature request related to a problem? Please describe.**
As Thoth Developer,

I would like to know how to access Thoth data on Ceph using thoth handlers so that I can work on my Jupyter notebooks, test scripts, etc..

**Describe the solution you'd like**
Add simple example on using thoth handler for data on Ceph in the README

**Describe alternatives you've considered**

**Additional context**

**Comment by codificat** [comment]
This is only waiting for the documentation to be updated in #2467.

/remove-triage needs-information
/triage accepted
/lifecycle active
/assign @xtuchyna

**Comment by codificat** [comment]
prow hiccup, trying again:
/remove-triage needs-information
/triage accepted
/lifecycle active
/assign @xtuchyna

**Comment by goern** [comment]
any updates on this?

**Comment by pacospace** [comment]
> any updates on this?

This need to be merged: https://github.com/thoth-station/storages/pull/2467 to be considered this done, cc @xtuchyna

**Comment by goern** [comment]
this seems to be done, feel free to reopen if required

/close
