### ISSUE TITLE
Cannot retrieve data from `opf-datacatalog-zero-backup` bucket [`rick` cluster]

### ISSUE THREAD

**Issue by xtuchyna** [thoth-station/storages#2452]
**Describe the bug**
When calling https://github.com/thoth-station/mi/blob/cf092832ea46e636816b4ecde54a10a4aec25ff4/srcopsmetrics/storage.py#L200

(which is essentially calling `retrieve_document(path)` on `CephStore` object) on a document that does not exist (but also on a document that does exist)

an `EndpointConnectionError` occurs.

**To Reproduce**
1. Get credentials for `opf-datacatalog-zero-backup` bucket at `rick` cluster (if you don't have them, please send me your `gpg` key and I will share it with you)

2. Initialize `CephStore` and try to retrieve doc (`thoth-storages==0.42.0`)
```
from thoth.storages.ceph import CephStore

s3 = CephStore(
    key_id=<access_key>,
    secret_key=<secret_access_key>,
    prefix='mi',
    host='https://ocs-storageclusst.cloud',
    bucket='opf-datacatalog-zero-backup')

s3.connect()

# for document that exists
s3.retrieve_document("TrafficViews.json")

# for document that does not exist
s3.retrieve_document("foo")
``` 
3. See error

**Expected behavior**
For document that exists, data should be retrieved.
For non-existing data, `NotFoundError` should be raised.

**LOGS**
```
Exception has occurred: EndpointConnectionError       (note: full exception trace is shown but execution is paused at: cli)
Could not connect to the endpoint URL: "https://ocs-storageclusst.cloud/opf-datacatalog-zero-backup/mi/srcopsmetrics/bot_knowledge/aicoe-aiops/ocp-ci-analysis/TrafficClones.json"
```

/kind bug

**Comment by xtuchyna** [comment]
Update: issue prevails in `thoth-storages==0.57.2` too

**Comment by pacospace** [comment]
It works for me, you are just using wrong endpoint. it should be `THOTH_S3_ENDPOINT_URL=http://ocs-storagecluster-cephobjectstore-openshift-storage.apps.rick.emea.operate-first.cloud`
