### ISSUE TITLE
Broken links in docs/syncs/README.rst

### ISSUE THREAD

**Issue by mayaCostantini** [thoth-station/storages#2469]
**Describe the bug**
The links towards the following JPG images are broken in the README file about syncs to Thoth Database : [solver](https://github.com/thoth-station/storages/tree/master/docs/thoth_sync_solver.jpg), [package-analyzer](https://github.com/thoth-station/storages/tree/master/docs/thoth_sync_package_analyzer.jpg), [package-extract](https://github.com/thoth-station/storages/tree/master/docs/thoth_sync_package_extract.jpg), [adviser](https://github.com/thoth-station/storages/tree/master/docs/thoth_sync_adviser.jpg), [dependency-monkey](https://github.com/thoth-station/storages/tree/master/docs/thoth_sync_dependency_monkey.jpg), [inspection](https://github.com/thoth-station/storages/tree/master/docs/thoth_sync_amun.jpg) and [schema for all components that syncs and create Python Packages in Thoth database](https://github.com/thoth-station/storages/tree/master/docs/thoth_syncs_togheter.jpg).

**To Reproduce**
Go to [docs/syncs/README.rst](https://github.com/thoth-station/storages/tree/master/docs/syncs) and click on the links mentioned above.

**Expected behavior**
The links redirect to the docs describing each process.

**Comment by codificat** [comment]
Thanks for reporting *and* fixing this @mayaCostantini!

/close
