### ISSUE TITLE
Rename thoth_s2i_*

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#2479]
**Is your feature request related to a problem? Please describe.**

To be agnostic to naming, we should remove s2i part from schema colmns.

Related: https://github.com/thoth-station/user-api/pull/1506#discussion_r749128539
Related: https://chat.google.com/room/AAAAVjnVXFk/jMLlhD0ftRk

**Describe the solution you'd like**

Rename thoth_s2i_ in the schema and related code parts to be agnostic to s2i naming.

- [ ] rename `thoth_s2i_*` to `thoth_*` in the database schema
  - [ ] create sqlalchemy migration
- [ ] adjust querying logic and syncing logic as necessary
- [ ] adjust endpoints on the user-api (the logic renaming in code should go away)
- [ ] adjust openapi user-api schema

**Comment by codificat** [comment]
Note that this implies a DB migration following the schema changes.

/remove-triage needs-information
/priority backlog
/help
/triage accepted

**Comment by mayaCostantini** [comment]
/close 
Closed by #2546
