### ISSUE TITLE
Revert ae4421b2 (upstream PR is merged)

### ISSUE THREAD

**Issue by VannTen** [thoth-station/storages#2653]
The commit ae4421b2 introduces thoth/storages/graph/postgres_utils.py, which
include a note to remove it when the upstream PR
(https://github.com/kvesteri/sqlalchemy-utils/pull/372) is merged.

Now that it is, can we revert that commit and remove postgres_util.py ?

**Comment by harshad16** [comment]
Yes, as per comment here: https://github.com/thoth-station/storages/blob/0f48239394a262ee995fbbe13486ad52e590e23a/thoth/storages/graph/postgres_utils.py#L3
we can revert it.
