### ISSUE TITLE
Inconsistency in Package schema?

### ISSUE THREAD

**Issue by CermakM** [thoth-station/storages#270]
In the jupyter example [Initial queries to JanusGraph](https://github.com/thoth-station/notebooks/blob/master/notebooks/Initial%20queries%20to%20JanusGraph.ipynb) we query JanusGraph like:

```python
gqr(
    g.V()
    .has('ecosystem', 'pypi')
    .or_(has('package_name', 'tensorflow'), has('package_name', 'tensorflow-gpu'))
    .order().by('package_version')
    .project('package', 'version').by('package_name').by('package_version')
    .toList()
).to_dataframe()
```

which produces error due to missing `package_version` attribute, which is not defined for class `Package` (see [models.py](https://github.com/thoth-station/storages/blob/master/thoth/storages/graph/models.py))

Do we want that schema to allow such query, or should we fix the notebook?

**Comment by fridex** [comment]
The query should be limited to only PythonPackageVersion vertexes, the package vertexes should be omitted. You can specify ``__label__`` in for this case:
```python
gqr(
    g.V()
    .has('ecosystem', 'pypi')
    .has('__label__', 'python_package_version')
    .or_(has('package_name', 'tensorflow'), has('package_name', 'tensorflow-gpu'))
    .order().by('package_version')
    .project('package', 'version').by('package_name').by('package_version')
    .toList()
).to_dataframe()
```
