### ISSUE TITLE
remove paths with negative observation from result set

### ISSUE THREAD

**Issue by goern** [thoth-station/storages#548]
We need to remove all the software stacks that have at least one negative observation on any edge/vertex of the graph.

https://github.com/thoth-station/storages/blob/e25cdd35336c09184951a9540fdc3a8815c2a197/thoth/storages/graph/janusgraph.py#L761

**Comment by fridex** [comment]
*in https://github.com/thoth-station/storages/blob/e25cdd35336c09184951a9540fdc3a8815c2a197/thoth/storages/graph/janusgraph.py#L814
