### ISSUE TITLE
Link PythonPackageIndex with PythonPackageVersion

### ISSUE THREAD

**Issue by fridex** [thoth-station/storages#556]
We should create an edge between `PythonPackageIndex` and `PythonPackageVersion` so that we can use this connection in queries. Also, this way we can easily check that each `PythonPackageVersion` is from an index known to Thoth (there is relevant `PythonPackageIndex` vertex). If somebody tries to install/use a `PythonPackageVersion` from an index not known to Thoth, Thoth should error out (only administrator of Thoth can add new `PythonPackageIndex` vertexes).

**Comment by fridex** [comment]
CC @pacospace

**Comment by pacospace** [comment]
Added new edge in #574

**Comment by fridex** [comment]
Implemented.
